import React from "react";
import { useParams } from "react-router-dom";
import DefaultPage from "../DefaultPage";
import DataGrid from "react-data-grid";
import format from "date-fns/format";

// const columns = [
//   { key: "id", name: "ID" },
//   { key: "title", name: "Title" },
// ];

const columns = [
  { key: "id", name: "#" },
  { key: "serviceOrProduct", name: "Service / Product" },
  { key: "serviceCompany", name: "Company" },
  { key: "billCode", name: "Bill" },
  { key: "createdAt", name: "Date" },
  { key: "price", name: "Price" },
  { key: "code", name: "Code" },
];

const rows = [
  {
    id: 0,
    serviceOrProduct: "Pakabos patikra",
    serviceCompany: "UAB KLASERA",
    billCode: "BOS Nr.2000588",
    createdAt: format(new Date("2020-12-31"), "yyyy.MM.dd"),
    price: 8.26.toFixed(2),
    code: "",
  },
  {
    id: 1,
    serviceOrProduct: "Oro radiatoriaus žarna",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 23.14.toFixed(2),
    code: "MP125",
  },
  {
    id: 2,
    serviceOrProduct: "Ratų guolių kompl.",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 128.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 3,
    serviceOrProduct: "P.K.rato guolio keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 28.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 4,
    serviceOrProduct: "Interkulertio žarnos keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 12.4.toFixed(2),
    code: "MP125",
  },
  {
    id: 5,
    serviceOrProduct: "Komp.Diagnostika",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 16.53.toFixed(2),
    code: "MP125",
  },
  {
    id: 6,
    serviceOrProduct: "Eksp.medžiaga",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 1.65.toFixed(2),
    code: "MP125",
  },
  {
    id: 7,
    serviceOrProduct: "Valytuvai",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 15.54.toFixed(2),
    code: "MP042",
  },
  {
    id: 8,
    serviceOrProduct: "Akumuliatorius",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 54.97.toFixed(2),
    code: "MP042",
  },
  {
    id: 0,
    serviceOrProduct: "Pakabos patikra",
    serviceCompany: "UAB KLASERA",
    billCode: "BOS Nr.2000588",
    createdAt: format(new Date("2020-12-31"), "yyyy.MM.dd"),
    price: 8.26.toFixed(2),
    code: "",
  },
  {
    id: 1,
    serviceOrProduct: "Oro radiatoriaus žarna",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 23.14.toFixed(2),
    code: "MP125",
  },
  {
    id: 2,
    serviceOrProduct: "Ratų guolių kompl.",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 128.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 3,
    serviceOrProduct: "P.K.rato guolio keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 28.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 4,
    serviceOrProduct: "Interkulertio žarnos keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 12.4.toFixed(2),
    code: "MP125",
  },
  {
    id: 5,
    serviceOrProduct: "Komp.Diagnostika",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 16.53.toFixed(2),
    code: "MP125",
  },
  {
    id: 6,
    serviceOrProduct: "Eksp.medžiaga",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 1.65.toFixed(2),
    code: "MP125",
  },
  {
    id: 7,
    serviceOrProduct: "Valytuvai",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 15.54.toFixed(2),
    code: "MP042",
  },
  {
    id: 8,
    serviceOrProduct: "Akumuliatorius",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 54.97.toFixed(2),
    code: "MP042",
  },
  {
    id: 0,
    serviceOrProduct: "Pakabos patikra",
    serviceCompany: "UAB KLASERA",
    billCode: "BOS Nr.2000588",
    createdAt: format(new Date("2020-12-31"), "yyyy.MM.dd"),
    price: 8.26.toFixed(2),
    code: "",
  },
  {
    id: 1,
    serviceOrProduct: "Oro radiatoriaus žarna",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 23.14.toFixed(2),
    code: "MP125",
  },
  {
    id: 2,
    serviceOrProduct: "Ratų guolių kompl.",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 128.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 3,
    serviceOrProduct: "P.K.rato guolio keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 28.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 4,
    serviceOrProduct: "Interkulertio žarnos keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 12.4.toFixed(2),
    code: "MP125",
  },
  {
    id: 5,
    serviceOrProduct: "Komp.Diagnostika",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 16.53.toFixed(2),
    code: "MP125",
  },
  {
    id: 6,
    serviceOrProduct: "Eksp.medžiaga",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 1.65.toFixed(2),
    code: "MP125",
  },
  {
    id: 7,
    serviceOrProduct: "Valytuvai",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 15.54.toFixed(2),
    code: "MP042",
  },
  {
    id: 8,
    serviceOrProduct: "Akumuliatorius",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 54.97.toFixed(2),
    code: "MP042",
  },
  {
    id: 0,
    serviceOrProduct: "Pakabos patikra",
    serviceCompany: "UAB KLASERA",
    billCode: "BOS Nr.2000588",
    createdAt: format(new Date("2020-12-31"), "yyyy.MM.dd"),
    price: 8.26.toFixed(2),
    code: "",
  },
  {
    id: 1,
    serviceOrProduct: "Oro radiatoriaus žarna",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 23.14.toFixed(2),
    code: "MP125",
  },
  {
    id: 2,
    serviceOrProduct: "Ratų guolių kompl.",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 128.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 3,
    serviceOrProduct: "P.K.rato guolio keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 28.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 4,
    serviceOrProduct: "Interkulertio žarnos keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 12.4.toFixed(2),
    code: "MP125",
  },
  {
    id: 5,
    serviceOrProduct: "Komp.Diagnostika",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 16.53.toFixed(2),
    code: "MP125",
  },
  {
    id: 6,
    serviceOrProduct: "Eksp.medžiaga",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 1.65.toFixed(2),
    code: "MP125",
  },
  {
    id: 7,
    serviceOrProduct: "Valytuvai",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 15.54.toFixed(2),
    code: "MP042",
  },
  {
    id: 8,
    serviceOrProduct: "Akumuliatorius",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 54.97.toFixed(2),
    code: "MP042",
  },
  {
    id: 0,
    serviceOrProduct: "Pakabos patikra",
    serviceCompany: "UAB KLASERA",
    billCode: "BOS Nr.2000588",
    createdAt: format(new Date("2020-12-31"), "yyyy.MM.dd"),
    price: 8.26.toFixed(2),
    code: "",
  },
  {
    id: 1,
    serviceOrProduct: "Oro radiatoriaus žarna",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 23.14.toFixed(2),
    code: "MP125",
  },
  {
    id: 2,
    serviceOrProduct: "Ratų guolių kompl.",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 128.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 3,
    serviceOrProduct: "P.K.rato guolio keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 28.93.toFixed(2),
    code: "MP125",
  },
  {
    id: 4,
    serviceOrProduct: "Interkulertio žarnos keitimas",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 12.4.toFixed(2),
    code: "MP125",
  },
  {
    id: 5,
    serviceOrProduct: "Komp.Diagnostika",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 16.53.toFixed(2),
    code: "MP125",
  },
  {
    id: 6,
    serviceOrProduct: "Eksp.medžiaga",
    serviceCompany: "UAB AUTOBOSAS",
    billCode: "IVA Nr.0002889",
    createdAt: format(new Date("2021-01-07"), "yyyy.MM.dd"),
    price: 1.65.toFixed(2),
    code: "MP125",
  },
  {
    id: 7,
    serviceOrProduct: "Valytuvai",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 15.54.toFixed(2),
    code: "MP042",
  },
  {
    id: 8,
    serviceOrProduct: "Akumuliatorius",
    serviceCompany: "Inter car",
    billCode: "L31210030295",
    createdAt: format(new Date("2021-04-23"), "yyyy.MM.dd"),
    price: 54.97.toFixed(2),
    code: "MP042",
  },
];

const InspectCar = () => {
  const { carId } = useParams();
  return (
    <DefaultPage>
      <DataGrid columns={columns} rows={rows} />
    </DefaultPage>
  );
};

export default InspectCar;
